apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: kubernetes.io/azure-file
  name: routes
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    secretNamespace: default
    shareName: routes
  capacity:
    storage: 10Gi
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-sample
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: sampleapp
  namespace: default
spec:
  containers:
  - name: sample  
    image: sample1res/sample:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /routes
      name: routes
  volumes:
  - name: routes
    persistentVolumeClaim:
      claimName: data-sample
